#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MedTrack.Resource", IsApplication=true)]

namespace MedTrack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AWSSDK_XMOBILE.Resource.String.ApplicationName = global::MedTrack.Resource.String.ApplicationName;
			global::AWSSDK_XMOBILE.Resource.String.Hello = global::MedTrack.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MedTrack.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MedTrack.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MedTrack.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int Alarm = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int AlarmSet = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AlarmSetatTime = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int MemberLogin = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int NewRegister = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int PatientLogin = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int PharmacyLogin = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int PhysicianLogin = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int WelcomeMessage = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int addPrescriptionLabel = 2131099668;
			
			// aapt resource value: 0x7f060022
			public const int addressLabel = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int addressText = 2131099683;
			
			// aapt resource value: 0x7f06002c
			public const int ageLabel = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int ageText = 2131099693;
			
			// aapt resource value: 0x7f060026
			public const int contactLabel = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int contactText = 2131099687;
			
			// aapt resource value: 0x7f06004f
			public const int contentFrame = 2131099727;
			
			// aapt resource value: 0x7f060036
			public const int disabilityLabel = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int disabilityText = 2131099703;
			
			// aapt resource value: 0x7f06002a
			public const int dobLabel = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int dobText = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int emergencyContactLabel = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int emergencyContactText = 2131099689;
			
			// aapt resource value: 0x7f060042
			public const int fNameLabel = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int fNameText = 2131099715;
			
			// aapt resource value: 0x7f06001e
			public const int firstNameLabel = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int firstNameText = 2131099679;
			
			// aapt resource value: 0x7f06002e
			public const int genderLabel = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int genderText = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int insuranceIDLabel = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int insuranceIDText = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int insuranceProviderLabel = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int insuranceProviderText = 2131099699;
			
			// aapt resource value: 0x7f060044
			public const int lNameLabel = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int lNameText = 2131099717;
			
			// aapt resource value: 0x7f060020
			public const int lastNameLabel = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int lastNameText = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int loginButton = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int loginID = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int loginIDLabel = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int memberText = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int newRegisterText = 2131099659;
			
			// aapt resource value: 0x7f060017
			public const int numOfDayLabel = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int numOfDayText = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int numOfTimesLabel = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int numOfTimesText = 2131099674;
			
			// aapt resource value: 0x7f060006
			public const int password = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int passwordLabel = 2131099653;
			
			// aapt resource value: 0x7f060034
			public const int pastAilmentsLabel = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int pastAilmentsText = 2131099701;
			
			// aapt resource value: 0x7f060012
			public const int patientIdLabel = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int patientIdText = 2131099667;
			
			// aapt resource value: 0x7f06003d
			public const int pharmacyAddress = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int pharmacyAddressText = 2131099710;
			
			// aapt resource value: 0x7f060039
			public const int pharmacyLabel = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int pharmacyText = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int pharmacyZipcode = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int pharmacyZipcodeText = 2131099708;
			
			// aapt resource value: 0x7f060046
			public const int phoneLabel = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int phoneText = 2131099719;
			
			// aapt resource value: 0x7f06001c
			public const int physicianName = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int prescribedByLabel = 2131099675;
			
			// aapt resource value: 0x7f060038
			public const int register = 2131099704;
			
			// aapt resource value: 0x7f06004e
			public const int registerPhysician = 2131099726;
			
			// aapt resource value: 0x7f060041
			public const int resgisterPharmacy = 2131099713;
			
			// aapt resource value: 0x7f06001d
			public const int scanAndAdd = 2131099677;
			
			// aapt resource value: 0x7f06004b
			public const int speciality = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int specialityLabel = 2131099722;
			
			// aapt resource value: 0x7f060016
			public const int startDate = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int startDateLabel = 2131099669;
			
			// aapt resource value: 0x7f06003f
			public const int stateLabel = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int stateText = 2131099712;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int welcome = 2131099665;
			
			// aapt resource value: 0x7f06004c
			public const int yearsLabel = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int yearsText = 2131099725;
			
			// aapt resource value: 0x7f060048
			public const int zipLabel = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int zipText = 2131099721;
			
			// aapt resource value: 0x7f060024
			public const int zipcodeLabel = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int zipcodeText = 2131099685;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlarmLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExistingMemberLogin = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewMemberRegister = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Patient = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PatientRegister = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PharmacyRegister = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PhysicianRegister = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
