#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MedTrack.Resource", IsApplication=true)]

namespace MedTrack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AWSSDK_XMOBILE.Resource.Id.contentFrame = global::MedTrack.Resource.Id.contentFrame;
			global::AWSSDK_XMOBILE.Resource.Layout.zxingscanneractivitylayout = global::MedTrack.Resource.Layout.zxingscanneractivitylayout;
			global::AWSSDK_XMOBILE.Resource.Layout.zxingscannerfragmentlayout = global::MedTrack.Resource.Layout.zxingscannerfragmentlayout;
			global::AWSSDK_XMOBILE.Resource.String.ApplicationName = global::MedTrack.Resource.String.ApplicationName;
			global::AWSSDK_XMOBILE.Resource.String.Hello = global::MedTrack.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MedTrack.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MedTrack.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MedTrack.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int AlarmSet = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int MemberLogin = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int NewRegister = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int PatientLogin = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int PharmacyLogin = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int PhysicianLogin = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int WelcomeMessage = 2131034121;
			
			// aapt resource value: 0x7f050025
			public const int addPrescription = 2131034149;
			
			// aapt resource value: 0x7f050019
			public const int addPrescriptionLabel = 2131034137;
			
			// aapt resource value: 0x7f05002b
			public const int addressLabel = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int addressText = 2131034156;
			
			// aapt resource value: 0x7f050035
			public const int ageLabel = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int ageText = 2131034166;
			
			// aapt resource value: 0x7f05002f
			public const int contactLabel = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int contactText = 2131034160;
			
			// aapt resource value: 0x7f050059
			public const int contentFrame = 2131034201;
			
			// aapt resource value: 0x7f05001d
			public const int datePicker1 = 2131034141;
			
			// aapt resource value: 0x7f05003f
			public const int disabilityLabel = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int disabilityText = 2131034176;
			
			// aapt resource value: 0x7f050033
			public const int dobLabel = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int dobText = 2131034164;
			
			// aapt resource value: 0x7f050031
			public const int emergencyContactLabel = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int emergencyContactText = 2131034162;
			
			// aapt resource value: 0x7f05004b
			public const int fNameLabel = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int fNameText = 2131034188;
			
			// aapt resource value: 0x7f050027
			public const int firstNameLabel = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int firstNameText = 2131034152;
			
			// aapt resource value: 0x7f050037
			public const int genderLabel = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int genderText = 2131034168;
			
			// aapt resource value: 0x7f050011
			public const int heading = 2131034129;
			
			// aapt resource value: 0x7f050039
			public const int insuranceIDLabel = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int insuranceIDText = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int insuranceProviderLabel = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int insuranceProviderText = 2131034172;
			
			// aapt resource value: 0x7f05004d
			public const int lNameLabel = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int lNameText = 2131034190;
			
			// aapt resource value: 0x7f050029
			public const int lastNameLabel = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int lastNameText = 2131034154;
			
			// aapt resource value: 0x7f050008
			public const int loginButton = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int memberText = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int newRegisterText = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int newpassword = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int newusername = 2131034131;
			
			// aapt resource value: 0x7f05001e
			public const int numOfDayLabel = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int numOfDayText = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int numOfTimesLabel = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int numOfTimesText = 2131034145;
			
			// aapt resource value: 0x7f050007
			public const int password = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int passwordLabel = 2131034118;
			
			// aapt resource value: 0x7f05003d
			public const int pastAilmentsLabel = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int pastAilmentsText = 2131034174;
			
			// aapt resource value: 0x7f050058
			public const int patientIDNumber = 2131034200;
			
			// aapt resource value: 0x7f050017
			public const int patientIdLabel = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int patientIDNumber = 2131034136;
			
			// aapt resource value: 0x7f050046
			public const int pharmacyAddress = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int pharmacyAddressText = 2131034183;
			
			// aapt resource value: 0x7f050042
			public const int pharmacyLabel = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int pharmacyText = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int pharmacyZipcode = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int pharmacyZipcodeText = 2131034181;
			
			// aapt resource value: 0x7f05004f
			public const int phoneLabel = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int phoneText = 2131034192;
			
			// aapt resource value: 0x7f050023
			public const int physicianName = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int prescribedByLabel = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int refillPrescription = 2131034150;
			
			// aapt resource value: 0x7f050041
			public const int register = 2131034177;
			
			// aapt resource value: 0x7f050015
			public const int registerButton = 2131034133;
			
			// aapt resource value: 0x7f050057
			public const int registerPhysician = 2131034199;
			
			// aapt resource value: 0x7f05004a
			public const int resgisterPharmacy = 2131034186;
			
			// aapt resource value: 0x7f05001a
			public const int rxLabel = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int rxNumber = 2131034139;
			
			// aapt resource value: 0x7f050024
			public const int scanAndAdd = 2131034148;
			
			// aapt resource value: 0x7f050054
			public const int speciality = 2131034196;
			
			// aapt resource value: 0x7f050053
			public const int specialityLabel = 2131034195;
			
			// aapt resource value: 0x7f05001c
			public const int startDateLabel = 2131034140;
			
			// aapt resource value: 0x7f050048
			public const int stateLabel = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int stateText = 2131034185;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int username = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int usernameLabel = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int usernamelabel1 = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int webview = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int welcome = 2131034134;
			
			// aapt resource value: 0x7f050055
			public const int yearsLabel = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int yearsText = 2131034198;
			
			// aapt resource value: 0x7f050051
			public const int zipLabel = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int zipText = 2131034194;
			
			// aapt resource value: 0x7f05002d
			public const int zipcodeLabel = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int zipcodeText = 2131034158;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_completed_refill = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_web_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AlarmLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExistingMemberLogin = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NewMemberRegister = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewUserRegistration = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Patient = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PatientLogin = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PatientRegister = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PharmacyRegister = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PhysicianRegister = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RefillScanLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int zxingscanneractivitylayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int zxingscannerfragmentlayout = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int PrescriptionRefill = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
